### ISSUE TITLE
How to deal with common playbook strings in the dataset

### ISSUE THREAD

**Issue by pjackson28** [canada-ca/digital-playbook-guide-numerique#129]
How should common strings in the playbook, such as "Checklist", "Implementation guides" and "Similar resources", be dealt with in the dataset?

Currently they are being dealt with separately but that likely isn't much help for dataset (and eventually API) users.

Should these common strings be embedded in the dataset or continue to be managed separately? If embedded in the dataset, should they be in a global section (so have a global section for guideline common strings) or repeated in each guideline instance? Having a global section would avoid duplication/sync issues and help to keep the file size down but would be less convenient for dataset users (would have to look in two different places in the dataset when outputting the guidelines). On the flip side, repeating the strings in each guideline instance would make it easier to use dataset (only have to look in one place) but would result in duplication, possible sync issues (one instance of the string could be made to be different than another instance) and likely a significant increase in dataset size (due to all the duplication).

Which approach is better and why? If the global approach is better, how should it be implemented? Should it mimic the dataset structure for the common parts (e.g., section headings in the rendered document) but just have a title property for the common string?

**Comment by pjackson28** [comment]
This same discussion should apply to common tags as well such as dpgn-section-guideline which is currently in each instance but maybe should be put in a global section instead since it shouldn't change from guideline to guideline.

**Comment by pjackson28** [comment]
The structure I'm thinking of going with for common strings and tags is the following:
```json
{
  "title": "Government of Canada Digital Playbook (draft)",
  "common": {
    "introduction": {
      "title": "Overview (draft)",
      "tags": ["dpgn-section-overview"]
    },
    "standards": {
      "title": "Digital Standards",
      "tags": ["dpgn-section-standard"],
      "introduction": {
        "tags": ["dpgn-section-intro-standard"]
      },
      "relatedguidelines": {
        "title": "Related guidelines",
        "tags": ["dpgn-section-guidelines-related"]
      },
      "guidelines": {
        "title": "Guidelines",
        "tags": ["dpgn-section-guideline"],
        "introduction": {
           "tags": ["dpgn-section-intro-guideline"]
        },
        "checklist": {
          "title": "Checklist",
          "tags": ["dpgn-section-checklist"]
        },
        "guides": {
          "title": "Implementation guides",
          "tags": ["dpgn-section-guides"]
        },
        "similar": {
          "title": "Similar resources",
          "tags": ["dpgn-section-similar"]
        }
      }
    }
  },
  "introduction": {
    "tags": [],
    "content": [
      {
```

**Comment by nschonni** [comment]
Not sure if it's just bikeshedding but Yaml might be easier to edit for this stuff. I think you could also use the https://jekyllrb.com/docs/templates/ `jsonify` to convert it back to JSON if you need the file format for API reasons

**Comment by pjackson28** [comment]
The current approach is to auto-generate the JSON file from an authored source, so the method of authoring could be YAML (currently we are using the markdown files as the source). We'll probably need to keep the JSON version for sharing the dataset and eventually API reasons.

**Comment by pjackson28** [comment]
Here is an updated version with some tweaks. Needed to add a level for common strings for individual standards and guidelines. Also move the top-level intro out of common since it was only being used once.
```json
{
  "title": "Government of Canada Digital Playbook (draft)",
  "common": {
    "standards": {
      "title": "Digital Standards",
      "tags": ["dpgn-section-standards"],
      "standard": {
        "tags": ["dpgn-section-standard"],
        "introduction": {
          "tags": ["dpgn-section-intro-standard"]
        },
        "relatedguidelines": {
          "title": "Related guidelines",
          "tags": ["dpgn-section-guidelines-related"]
        },
        "guidelines": {
          "title": "Guidelines",
          "tags": ["dpgn-section-guidelines"],
          "guideline": {
            "tags": ["dpgn-section-guideline"],
            "introduction": {
               "tags": ["dpgn-section-intro-guideline"]
            },
            "checklist": {
              "title": "Checklist",
              "tags": ["dpgn-section-checklist"]
            },
            "guides": {
              "title": "Implementation guides",
              "tags": ["dpgn-section-guides"]
            },
            "similar": {
              "title": "Similar resources",
              "tags": ["dpgn-section-similar"]
            }
          }
        }
      }
    }
  },
  "introduction": {
    "title": "Overview (draft)",
    "tags": ["dpgn-section-overview"],
```
