### ISSUE TITLE
Another resource for Similar resources of "5. Work in the open by default (draft)"

### ISSUE THREAD

**Issue by mgifford** [canada-ca/digital-playbook-guide-numerique#211]
In 5. Work in the open by default (draft)

https://canada-ca.github.io/digital-playbook-guide-numerique/views-vues/standards-normes/en/5-work-in-open-by-default.html

I think it is worth adding https://sourcecode.cio.gov/

**Comment by pjackson28** [comment]
Good idea! I merged in the pull request from @smellems to add that link (will become visible after the dataset is regenerated). Closing the issue since the link was added and will be visible soon.
