### ISSUE TITLE
View source on GitHub

### ISSUE THREAD

**Issue by mgifford** [canada-ca/digital-playbook-guide-numerique#215]
Links in:
  https://canada-ca.github.io/digital-playbook-guide-numerique/views-vues/standards-normes/en/2-build-in-accessibility-from-start.html

to "View source on GitHub"

go to https://github.com/canada-ca/digital-playbook-guide-numerique/blob/master/views-vues/standards-normes/en/2-build-in-accessibility-from-start.md

Which isn't actually markdown. Not clear where that text actually is.

Usually the view the source would go to the raw document where you can see either the markdown or HTML. This goes to neither of them.

**Comment by pjackson28** [comment]
Good point, that was the result of switching to pages generated from the dataset and not correcting the auto-generated view source links. Will correct those links so they point to the authored source .md files again.

**Comment by pjackson28** [comment]
I merged in a fix that creates "View content source" and "View template source" links since they are separate .md files (one being the knowledge base content source and the other controlling the view output).

Thank you for reporting the issue!
