### ISSUE TITLE
Build failing because link check is having problems with URIs passed through Kramdown attributes

### ISSUE THREAD

**Issue by pjackson28** [canada-ca/digital-playbook-guide-numerique#239]
@nschonni The link checker is getting tripped up by URIs passed through Kramdown attributes (e.g., data-content-source-uri="someurl"). The link check seems to escape the last quotation mark and include any characters after it when checking the URL. There can be no space between the last attribute and the curly bracket, otherwise the last attribute will be ignored. Will try changing the order of attributes but is there some way to prevent the link checker from getting tripped up?

Here is an example of the link checking failing:
https://travis-ci.org/canada-ca/digital-playbook-guide-numerique/builds/397012941?utm_source=github_status&utm_medium=notification

**Comment by pjackson28** [comment]
Reordering the attributes didn't fix it. It still escapes the quotation mark even when there is a space after.

**Comment by nschonni** [comment]
I don't think I've hit that before, but maybe try bumping the install to the very latest. Doesn't look like anything related is bumped, but can't hurt.
Otherwise it might be a bug with https://github.com/tcort/markdown-link-extractor

**Comment by pjackson28** [comment]
I threw a bunch of patterns in the JSON file and one of them worked. Not sure which one but the build passed.
