### ISSUE TITLE
Single page view of digital standards missing French

### ISSUE THREAD

**Issue by smellems** [canada-ca/digital-playbook-guide-numerique#295]
The French version of
https://canada-ca.github.io/digital-playbook-guide-numerique/views-vues/single-page-seule/en/digital-standards.html

Shows a 404
https://canada-ca.github.io/digital-playbook-guide-numerique/views-vues/single-page-seule/fr/guide-numerique.html

**Comment by pjackson28** [comment]
@smellems Thanks for catching that! Turns out the French filename was missing an "s" so resulted in broken links. PR #296 will fix the filename as well as the English and French language change links (which were using the old filenames so resulted in broken links as well).
