### ISSUE TITLE
(Page: Is Agile Right for My Project? (draft))

### ISSUE THREAD

**Issue by jvanulde** [canada-ca/digital-playbook-guide-numerique#324]
It might be prudent to define terms such as "Product Owner". While many of us that are well versed and experienced in Agile methods understand these terms others might not. A tool-tip or perhaps a glossary is sufficient in my view. This wouldn't necessitate the requirement for one to be well educated on Agile methods prior to using the tool.

**Comment by pjackson28** [comment]
@jvanulde That sounds like a good idea. Do you know of a good existing source for definitions for those terms?

**Comment by pjackson28** [comment]
@jvanulde I added a definition for product owner (from the Ontario government). What do you think of the approach? Anything else that should have a definition?

**Comment by jvanulde** [comment]
Looks good @pjackson28

**Comment by pjackson28** [comment]
Thanks @jvanulde. Should the issue be closed?
