### ISSUE TITLE
(Page: Is Agile Right for My Project? (draft))

### ISSUE THREAD

**Issue by paulywill** [canada-ca/digital-playbook-guide-numerique#373]
A mention or reference to Jeff Sutherland and/or his book, "Scrum: The Art of Doing Twice the Work in Half the Time", might be worthwhile. He is considered one of the founders or Agile methodology.

**Comment by pjackson28** [comment]
Thank you for the suggestion. So far we've only been providing links to content that can be found online so people can quickly reference it. Is any of the content available to view online?

**Comment by paulywill** [comment]
https://www.thinglink.com/scene/535528547733733377?buttonSource=viewLimits

**Comment by pjackson28** [comment]
Thank you for the suggestion. I added a link to this under the Implementation guides in [2.1 Develop services using agile, iterative and user-centred methods](https://canada-ca.github.io/digital-playbook-guide-numerique/views-vues/standards-normes/en/2-iterate-improve-frequently.html#develop-services-using-agile-iterative-and-user-centred-methods).
