### ISSUE TITLE
Missing question label

### ISSUE THREAD

**Issue by tinok** [canada-ca/digital-playbook-guide-numerique#393]
While testing the form I found there is no label for question 22 - see image:

![image](https://user-images.githubusercontent.com/673511/54562500-85809380-499d-11e9-89a5-1eae7c9ad9ad.png)

**Comment by gcharest** [comment]
Hi @tinok 

Thanks for noting this! The project is slowly moving away from the Digital Playbook as the assessment model will become its own tool.

Please visit this link for the project: https://github.com/canada-ca/aia-eia-js

And this link for the latest version: https://canada-ca.github.io/aia-eia-js/ 

Thanks,

Guillaume
