### ISSUE TITLE
The links to wiki.ic.gc.ca are unavailable to other departments

### ISSUE THREAD

**Issue by nschonni** [canada-ca/digital-playbook-guide-numerique#70]
The link under https://github.com/canada-ca/digital-playbook-guide-numerique/blob/085a41397de9a378bfea79a8c252e2a4308b10a8/en/4-empower-staff-deliver-better-services.md#implementation-guides-2 doesn't appear to work for people in other departments.

If this gets replaced, the check-links.js can also be updated to not exclude those links from failing the build.

**Comment by pjackson28** [comment]
Fixed  by PRs #72 and #84
